name: "build-test"

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    types:
      - opened
    branches:
      - 'main'

jobs:
  build-test:
    name: "Build -> Test"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build gradle.properties
        run: echo 'android.useAndroidX=true' > gradle.properties

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Tests
        run: ./gradlew test -PauthToken=${{ secrets.ACCESS_TOKEN }}
